#%% SEQ2SEQ CONFIG


dataset:
    path: '../data/trainn/'
    train: 'test.csv'
    dev: 'dev.csv'
    test: 'test.csv'

    embeddings:
        use: True
        update: False


    max_length: 14
    max_vocab: 500000

model:
    hidden_size: 256
    bidirectional: True

    device: 'cuda'
    # 'lstm' or 'gru'
    rnn_cell: 'lstm'

    # 'NLLL' for Negative log likelihood or 'Perp' for perplexity
    loss: 'NLLL'

    # 'Adam' or 'SGD'
    optimizer: 'Adam'

    scheduler:
        enabled: True
        rate: 1

    use_attention: True
    n_layers: 2
    dropout_input: 0.25
    dropout_output: 0.25

    variable_lengths: True

train:
    lr: 0.0013
    teacher_forcing_ratio: 1.25
    batch_size: 64
    epoch: 10
    early_stop_threshold: 2
    print_every: 500
    checkpoint_every: 1

save_dir: './Experiments'
